### PR TITLE
Return correct byte offset from IndexIn

### PR DESCRIPTION
**Pull request by shezadkhan137**
According to the [LSP Spec](https://microsoft.github.io/language-server-protocol/specification#textDocuments)
Character Offsets are based on UTF-16 string representations. The
current IndexIn assumes the Character is a byte offset leading to
incorrect state in the Language Server.

### CODE REVIEW

**Comment by tliron** [comment]
Thanks! But this looks like a very complicated solution. Is there really nothing in the [utf16 package](https://pkg.go.dev/unicode/utf16) that can handle this?

**Comment by shezadkhan137** [comment]
Yeh, honestly I wondered the same about the utf16 package. I _think_ the answer is no because the Decode/Encode seems to just work on `[]uint16`and return `[]rune`, neither of which tells us the number of code units? I may be wrong though.

The code I actually used is modified from the actual [gopls](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.5:internal/span/utf16.go;l=70) implementation, as I figured that was the most straightforward way of figuring out how to do it.  FWIW, it just boils down to double counting the utf8 bytes when the rune is over `0x10000`.

**Comment by tliron** [comment]
Hm, this is interesting problem. I'm absolutely fine with accepting this code as it is, if it does work (and it seems to). Could you just fix the PR to add a comment about where you took the code from? That way in the future maybe someone can take another look and find a more straightforward solution.

**Comment by shezadkhan137** [comment]
@tliron I've updated the comments to explain where the code has been taken from.

**Comment by tliron** [comment]
@shezadkhan137 Thank you very much for your contribution!

**Comment by mickael-menu** [comment]
Perfect timing! I got a bug report that was caused by this: https://github.com/mickael-menu/zk/issues/72

**Pull request merged**
